# -*- coding: utf-8 -*-

"""
Настройки для карты: маппинги названий, исторические территории, альтернативные названия
"""

# ===== АЛЬТЕРНАТИВНЫЕ НАЗВАНИЯ СТРАН В GEOJSON =====
COUNTRY_NAME_ALTERNATIVES = {
    "Tanzania": ["Tanzania", "United Republic of Tanzania", "Tanzania, United Republic of"],
    "Kenya": ["Kenya", "Republic of Kenya"],
    "Uganda": ["Uganda", "Republic of Uganda"],
    "Vietnam": ["Vietnam", "Viet Nam", "Socialist Republic of Vietnam"],
    "Laos": ["Laos", "Lao People's Democratic Republic", "Lao PDR"],
    "Cambodia": ["Cambodia", "Kingdom of Cambodia"],
    "Russia": ["Russia", "Russian Federation"],
    "Ukraine": ["Ukraine"],
    "Belarus": ["Belarus", "Republic of Belarus"],
    "Kazakhstan": ["Kazakhstan", "Republic of Kazakhstan"],
    "Germany": ["Germany", "Federal Republic of Germany"],
    "France": ["France", "French Republic"],
    "Italy": ["Italy", "Italian Republic"],
    "United Kingdom": ["United Kingdom", "United Kingdom of Great Britain and Northern Ireland"],
    "Taiwan": ["Taiwan", "Taiwan, Province of China"],
    "China": ["China", "People's Republic of China"],
}


# ===== МАППИНГ РУССКИХ НАЗВАНИЙ НА АНГЛИЙСКИЕ =====
RUSSIAN_TO_ENGLISH = {
    # Европа
    "Нидерландские Антильские острова": "Netherlands Antilles",
    "Швейцария": "Switzerland",
    "Россия": "Russia",
    "Украина": "Ukraine",
    "Беларусь": "Belarus",
    "Молдова": "Moldova",
    "Грузия": "Georgia",
    "Армения": "Armenia",
    "Азербайджан": "Azerbaijan",
    "Казахстан": "Kazakhstan",
    "Киргизия": "Kyrgyzstan",
    "Таджикистан": "Tajikistan",
    "Туркменистан": "Turkmenistan",
    "Узбекистан": "Uzbekistan",
    "Польша": "Poland",
    "Финляндия": "Finland",
    "Литва": "Lithuania",
    "Латвия": "Latvia",
    "Эстония": "Estonia",
    "Австрия": "Austria",
    "Венгрия": "Hungary",
    "Чехия": "Czech Republic",
    "Словакия": "Slovakia",
    "Словения": "Slovenia",
    "Хорватия": "Croatia",
    "Босния и Герцеговина": "Bosnia and Herzegovina",
    "Румыния": "Romania",
    "Италия": "Italy",
    "Сербия": "Serbia",
    "Черногория": "Montenegro",
    "Северная Македония": "North Macedonia",
    "Косово": "Kosovo",
    "Албания": "Albania",
    "Греция": "Greece",
    "Болгария": "Bulgaria",
    "Турция": "Turkey",
    "Кипр": "Cyprus",
    "Германия": "Germany",
    "Франция": "France",
    "Бельгия": "Belgium",
    "Нидерланды": "Netherlands",
    "Люксембург": "Luxembourg",
    "Дания": "Denmark",
    "Норвегия": "Norway",
    "Швеция": "Sweden",
    "Исландия": "Iceland",
    "Ирландия": "Ireland",
    "Великобритания": "United Kingdom",
    "Англия": "United Kingdom",
    "Испания": "Spain",
    "Португалия": "Portugal",
    "Андорра": "Andorra",
    "Монако": "Monaco",
    "Сан-Марино": "San Marino",
    "Ватикан": "Vatican City",
    "Мальта": "Malta",
    
    # Азия
    "Китай": "China",
    "Тайвань": "Taiwan",
    "Китай республика": "Taiwan",
    "Япония": "Japan",
    "Южная Корея": "South Korea",
    "Северная Корея": "North Korea",
    "Индия": "India",
    "Пакистан": "Pakistan",
    "Бангладеш": "Bangladesh",
    "Мьянма": "Myanmar",
    "Шри-Ланка": "Sri Lanka",
    "Таиланд": "Thailand",
    "Вьетнам": "Vietnam",
    "Лаос": "Laos",
    "Камбоджа": "Cambodia",
    "Малайзия": "Malaysia",
    "Сингапур": "Singapore",
    "Бруней": "Brunei",
    "Индонезия": "Indonesia",
    "Филиппины": "Philippines",
    "Непал": "Nepal",
    "Бутан": "Bhutan",
    "Монголия": "Mongolia",
    "Афганистан": "Afghanistan",
    "Иран": "Iran",
    "Ирак": "Iraq",
    "Сирия": "Syria",
    "Ливан": "Lebanon",
    "Израиль": "Israel",
    "Иордания": "Jordan",
    "Саудовская Аравия": "Saudi Arabia",
    "Йемен": "Yemen",
    "Оман": "Oman",
    "ОАЭ": "United Arab Emirates",
    "Катар": "Qatar",
    "Кувейт": "Kuwait",
    "Бахрейн": "Bahrain",
    "Палестина": "Palestine",
    
    # Африка
    "Кения": "Kenya",
    "Уганда": "Uganda",
    "Танзания": "Tanzania",
    "Руанда": "Rwanda",
    "Бурунди": "Burundi",
    "Сомали": "Somalia",
    "Эфиопия": "Ethiopia",
    "Эритрея": "Eritrea",
    "Джибути": "Djibouti",
    "Судан": "Sudan",
    "Южный Судан": "South Sudan",
    "Египет": "Egypt",
    "Ливия": "Libya",
    "Тунис": "Tunisia",
    "Алжир": "Algeria",
    "Марокко": "Morocco",
    "Мавритания": "Mauritania",
    "Сенегал": "Senegal",
    "Гамбия": "Gambia",
    "Гвинея": "Guinea",
    "Гвинея-Бисау": "Guinea-Bissau",
    "Сьерра-Леоне": "Sierra Leone",
    "Либерия": "Liberia",
    "Кот-д'Ивуар": "Ivory Coast",
    "Гана": "Ghana",
    "Того": "Togo",
    "Бенин": "Benin",
    "Нигер": "Niger",
    "Буркина-Фасо": "Burkina Faso",
    "Мали": "Mali",
    "Чад": "Chad",
    "Камерун": "Cameroon",
    "ЦАР": "Central African Republic",
    "Габон": "Gabon",
    "Республика Конго": "Republic of Congo",
    "ДР Конго": "Democratic Republic of the Congo",
    "Ангола": "Angola",
    "Намибия": "Namibia",
    "Ботсвана": "Botswana",
    "Зимбабве": "Zimbabwe",
    "Замбия": "Zambia",
    "Малави": "Malawi",
    "Мозамбик": "Mozambique",
    "Мадагаскар": "Madagascar",
    "Коморы": "Comoros",
    "Маврикий": "Mauritius",
    "Сейшелы": "Seychelles",
    "ЮАР": "South Africa",
    "Эсватини": "Eswatini",
    "Лесото": "Lesotho",
    "Кабо-Верде": "Cabo Verde",
    "Сан-Томе и Принсипи": "Sao Tome and Principe",
    "Южно-Африканская Республика": "South Africa",
    "Трансвааль": "South Africa",
    "Республика Трансвааль": "South Africa",
    
    # Америка
    "США": "United States of America",
    "Канада": "Canada",
    "Мексика": "Mexico",
    "Гватемала": "Guatemala",
    "Белиз": "Belize",
    "Гондурас": "Honduras",
    "Сальвадор": "El Salvador",
    "Никарагуа": "Nicaragua",
    "Коста-Рика": "Costa Rica",
    "Панама": "Panama",
    "Куба": "Cuba",
    "Ямайка": "Jamaica",
    "Гаити": "Haiti",
    "Доминикана": "Dominican Republic",
    "Пуэрто-Рико": "Puerto Rico",
    "Багамы": "Bahamas",
    "Тринидад и Тобаго": "Trinidad and Tobago",
    "Барбадос": "Barbados",
    "Сент-Люсия": "Saint Lucia",
    "Гренада": "Grenada",
    "Сент-Винсент и Гренадины": "Saint Vincent and the Grenadines",
    "Доминика": "Dominica",
    "Антигуа и Барбуда": "Antigua and Barbuda",
    "Сент-Китс и Невис": "Saint Kitts and Nevis",
    "Колумбия": "Colombia",
    "Венесуэла": "Venezuela",
    "Гайана": "Guyana",
    "Суринам": "Suriname",
    "Французская Гвиана": "French Guiana",
    "Эквадор": "Ecuador",
    "Перу": "Peru",
    "Боливия": "Bolivia",
    "Бразилия": "Brazil",
    "Парагвай": "Paraguay",
    "Чили": "Chile",
    "Аргентина": "Argentina",
    "Уругвай": "Uruguay",
    
    # Океания
    "Австралия": "Australia",
    "Новая Зеландия": "New Zealand",
    "Папуа - Новая Гвинея": "Papua New Guinea",
    "Фиджи": "Fiji",
    "Соломоновы Острова": "Solomon Islands",
    "Вануату": "Vanuatu",
    "Самоа": "Samoa",
    "Тонга": "Tonga",
    "Кирибати": "Kiribati",
    "Микронезия": "Micronesia",
    "Маршалловы Острова": "Marshall Islands",
    "Палау": "Palau",
    "Науру": "Nauru",
    "Тувалу": "Tuvalu",
    "Новая Каледония": "New Caledonia",
    "Французская Полинезия": "French Polynesia",
    "Острова Кука": "Cook Islands",
    "Токелау": "Tokelau",
    "Ниуэ": "Niue",
}


# ===== МАППИНГ АНГЛИЙСКИХ НАЗВАНИЙ НА РУССКИЕ =====
ENGLISH_TO_RUSSIAN = {v: k for k, v in RUSSIAN_TO_ENGLISH.items()}

# Дополнительные маппинги для GeoJSON
ENGLISH_TO_RUSSIAN.update({
    "United States of America": "США",
    "United Kingdom": "Великобритания",
    "Russian Federation": "Россия",
    "Czech Republic": "Чехия",
    "South Korea": "Южная Корея",
    "North Korea": "Северная Корея",
    "Ivory Coast": "Кот-д'Ивуар",
    "Democratic Republic of the Congo": "ДР Конго",
    "Republic of Congo": "Республика Конго",
    "Central African Republic": "ЦАР",
    "Sao Tome and Principe": "Сан-Томе и Принсипи",
    "Cabo Verde": "Кабо-Верде",
    "Eswatini": "Эсватини",
})


# ===== ВСТРОЕННЫЙ МАППИНГ ИСТОРИЧЕСКИХ ТЕРРИТОРИЙ =====
HISTORICAL_MAPPING = {
    # ===== ЕВРОПА =====
    "Российская Империя": ["Russia", "Ukraine", "Belarus", "Moldova", "Georgia", "Armenia", "Azerbaijan", "Kazakhstan", "Kyrgyzstan", "Tajikistan", "Turkmenistan", "Uzbekistan", "Poland", "Finland", "Lithuania", "Latvia", "Estonia"],
    "СССР": ["Russia", "Ukraine", "Belarus", "Moldova", "Georgia", "Armenia", "Azerbaijan", "Kazakhstan", "Kyrgyzstan", "Tajikistan", "Turkmenistan", "Uzbekistan", "Lithuania", "Latvia", "Estonia"],
    "Австро-Венгрия": ["Austria", "Hungary", "Czech Republic", "Slovakia", "Slovenia", "Croatia", "Bosnia and Herzegovina", "Poland", "Romania", "Italy", "Ukraine"],
    "Германская Империя": ["Germany", "Poland", "France", "Denmark", "Belgium", "Lithuania", "Russia", "Czech Republic"],
    "Третий Рейх": ["Germany", "Austria", "Czech Republic", "Poland", "France", "Belgium", "Netherlands", "Luxembourg", "Denmark", "Norway", "Slovenia"],
    "Пруссия": ["Germany", "Poland", "Russia", "Lithuania", "Czech Republic"],
    "Югославия": ["Serbia", "Croatia", "Slovenia", "Bosnia and Herzegovina", "Montenegro", "North Macedonia", "Kosovo"],
    "Чехословакия": ["Czech Republic", "Slovakia"],
    "ГДР": ["Germany"],
    "Османская Империя": ["Turkey", "Greece", "Bulgaria", "Romania", "Serbia", "Croatia", "Bosnia and Herzegovina", "Albania", "Syria", "Iraq", "Lebanon", "Israel", "Jordan", "Saudi Arabia", "Yemen", "United Arab Emirates", "Kuwait", "Qatar", "Bahrain", "Oman", "Libya", "Tunisia", "Algeria", "Egypt", "Sudan", "Eritrea", "Djibouti", "Somalia", "Cyprus"],
    "Византийская Империя": ["Turkey", "Greece", "Bulgaria", "Romania", "Serbia", "Albania", "North Macedonia", "Cyprus", "Egypt", "Libya", "Syria", "Lebanon", "Israel", "Jordan", "Palestine", "Italy"],
    "Англия": ["United Kingdom"],
    "Великобритания": ["United Kingdom"],
    "Южно-Африканская Республика": ["South Africa"],
    "Трансвааль": ["South Africa"],
    "Республика Трансвааль": ["South Africa"],
    "ЮАР (Трансвааль)": ["South Africa"],
    # ===== АЗИЯ =====
    "Французский Индокитай": ["Vietnam", "Laos", "Cambodia"],
    "Индия - Британская": ["India", "Pakistan", "Bangladesh", "Myanmar", "Sri Lanka"],
    "Голландская Ост-Индия": ["Indonesia"],
    "Малайская Федерация": ["Malaysia", "Singapore", "Brunei"],
    "Северный Вьетнам": ["Vietnam"],
    "Южный Вьетнам": ["Vietnam"],
    "Корейская Империя": ["South Korea", "North Korea"],
    "Маньчжоу-Го": ["China", "Russia"],
    "Тибет": ["China", "India", "Nepal", "Bhutan"],
    "Сикким": ["India"],
    "Британская Малайя": ["Malaysia", "Singapore"],
    "Бирма": ["Myanmar"],
    "Цейлон": ["Sri Lanka"],
    "Сиам": ["Thailand"],
    "Кхмерская Империя": ["Cambodia", "Thailand", "Laos", "Vietnam"],
    "Японская Империя": ["Japan", "South Korea", "North Korea", "Taiwan", "China", "Russia", "Micronesia", "Palau", "Marshall Islands"],
    "Китай республика": ["Taiwan", "China"],
    "Тайвань": ["Taiwan"],
    
    # ===== АФРИКА =====
    "Британская Восточная Африка": ["Kenya", "Uganda", "Tanzania"],
    "Французская Западная Африка": ["Senegal", "Mali", "Burkina Faso", "Niger", "Guinea", "Ivory Coast", "Benin", "Mauritania"],
    "Французская Экваториальная Африка": ["Gabon", "Republic of Congo", "Central African Republic", "Chad"],
    "Бельгийское Конго": ["Democratic Republic of the Congo"],
    "Германская Восточная Африка": ["Tanzania", "Rwanda", "Burundi"],
    "Германская Юго-Западная Африка": ["Namibia"],
    "Итальянская Ливия": ["Libya"],
    "Итальянская Восточная Африка": ["Ethiopia", "Eritrea", "Somalia", "Djibouti"],
    "Португальская Ангола": ["Angola"],
    "Португальский Мозамбик": ["Mozambique"],
    "Родезия": ["Zimbabwe"],
    "Ньясаленд": ["Malawi"],
    "Северная Родезия": ["Zambia"],
    "Занзибар": ["Tanzania"],
    "Юго-Западная Африка": ["Namibia"],
    "Капская колония": ["South Africa"],
    "Оранжевое Свободное Государство": ["South Africa"],
    "Трансвааль": ["South Africa"],
    "Французский Алжир": ["Algeria"],
    "Французский Марокко": ["Morocco"],
    "Французский Тунис": ["Tunisia"],
    "Испанский Марокко": ["Morocco"],
    "Египетский Судан": ["Sudan", "South Sudan"],
    "Англо-Египетский Судан": ["Sudan", "South Sudan"],
    
    # ===== АМЕРИКА =====
    "Вест-Индская Федерация": ["Jamaica", "Trinidad and Tobago", "Barbados", "Saint Lucia", "Grenada", "Saint Vincent and the Grenadines", "Dominica", "Antigua and Barbuda", "Saint Kitts and Nevis"],
    "Британская Гвиана": ["Guyana"],
    "Голландская Гвиана": ["Suriname"],
    "Французская Гвиана": ["French Guiana"],
    "Британский Гондурас": ["Belize"],
    "Техас": ["United States"],
    "Калифорнийская республика": ["United States"],
    "Конфедеративные Штаты Америки": ["United States"],
    "Великая Колумбия": ["Colombia", "Venezuela", "Ecuador", "Panama", "Peru", "Brazil"],
    "Перу-Боливийская конфедерация": ["Peru", "Bolivia"],
    "Центральноамериканская федерация": ["Guatemala", "El Salvador", "Honduras", "Nicaragua", "Costa Rica"],
    
    # ===== ОКЕАНИЯ =====
    "Британские Соломоновы острова": ["Solomon Islands"],
    "Британские Фиджи": ["Fiji"],
    "Британские Новые Гебриды": ["Vanuatu"],
    "Германская Новая Гвинея": ["Papua New Guinea"],
    "Германское Самоа": ["Samoa"],
    "Британское Самоа": ["Samoa"],
    "Гуам": ["Guam"],
    "Науру": ["Nauru"],
    "Острова Кука": ["Cook Islands"],
    "Токелау": ["Tokelau"],
    "Ниуэ": ["Niue"],
}


# ===== КООРДИНАТЫ СТРАН ДЛЯ МАРКЕРОВ =====
COUNTRY_COORDINATES = {
    "Южно-Африканская Республика": [-26.0, 28.0],  # Центр Трансвааля (Претория)
    "Трансвааль": [-26.0, 28.0],
    "Республика Трансвааль": [-26.0, 28.0],
    "Россия": [60.0, 90.0],
    "США": [37.09, -95.71],
    "Великобритания": [54.0, -2.0],
    "Германия": [51.0, 10.0],
    "Франция": [46.0, 2.0],
    "Италия": [42.0, 12.0],
    "Испания": [40.0, -4.0],
    "Китай": [35.0, 105.0],
    "Япония": [36.0, 138.0],
    "Канада": [56.0, -106.0],
    "Австралия": [-25.0, 135.0],
    "Индия": [20.0, 77.0],
    "Бразилия": [-10.0, -55.0],
    "Мексика": [23.0, -102.0],
    "Турция": [39.0, 35.0],
    "Египет": [26.0, 30.0],
    "ЮАР": [-29.0, 24.0],
    "Кения": [1.0, 38.0],
    "Уганда": [1.0, 32.0],
    "Танзания": [-6.0, 35.0],
    "Вьетнам": [16.0, 108.0],
    "Лаос": [18.0, 105.0],
    "Камбоджа": [12.0, 105.0],
    "Тунис": [34.0, 9.0],
    "Алжир": [28.0, 3.0],
    "Марокко": [32.0, -6.0],
    "Ливия": [25.0, 17.0],
    "Украина": [49.0, 32.0],
    "Беларусь": [53.0, 28.0],
    "Казахстан": [48.0, 68.0],
    "Швеция": [62.0, 15.0],
    "Норвегия": [62.0, 10.0],
    "Финляндия": [64.0, 26.0],
    "Дания": [56.0, 10.0],
    "Польша": [52.0, 19.0],
    "Чехия": [50.0, 15.0],
    "Австрия": [47.5, 13.5],
    "Швейцария": [47.0, 8.0],
    "Нидерланды": [52.0, 5.0],
    "Бельгия": [50.5, 4.5],
    "Португалия": [39.5, -8.0],
    "Греция": [39.0, 22.0],
    "Ирландия": [53.0, -8.0],
    "Венгрия": [47.0, 19.0],
    "Румыния": [46.0, 25.0],
    "Болгария": [43.0, 25.0],
    "Сербия": [44.0, 21.0],
    "Хорватия": [45.0, 15.0],
    "Словения": [46.0, 15.0],
    "Словакия": [48.5, 19.5],
    "Израиль": [31.0, 35.0],
    "Саудовская Аравия": [24.0, 45.0],
    "ОАЭ": [24.0, 54.0],
    "Иран": [32.0, 53.0],
    "Ирак": [33.0, 44.0],
    "Сирия": [35.0, 38.0],
    "Ливан": [33.8, 35.9],
    "Иордания": [31.0, 36.0],
    "Аргентина": [-34.0, -64.0],
    "Чили": [-35.0, -71.0],
    "Колумбия": [4.0, -72.0],
    "Венесуэла": [8.0, -66.0],
    "Перу": [-9.0, -75.0],
    "Эквадор": [-1.0, -78.0],
    "Боливия": [-17.0, -65.0],
    "Парагвай": [-23.0, -58.0],
    "Уругвай": [-32.5, -55.5],
    "Куба": [21.5, -80.0],
    "Ямайка": [18.0, -77.5],
    "Гаити": [19.0, -72.5],
    "Доминикана": [19.0, -70.5],
    "Пуэрто-Рико": [18.2, -66.5],
    "Багамы": [24.0, -76.0],
    "Тринидад и Тобаго": [10.5, -61.0],
    "Барбадос": [13.1, -59.5],
    "Филиппины": [13.0, 122.0],
    "Индонезия": [-5.0, 120.0],
    "Малайзия": [4.0, 102.0],
    "Таиланд": [15.0, 100.0],
    "Монголия": [46.0, 105.0],
    "Южная Корея": [36.0, 128.0],
    "Северная Корея": [40.0, 127.0],
    "Афганистан": [33.0, 65.0],
    "Пакистан": [30.0, 70.0],
    "Бангладеш": [24.0, 90.0],
    "Мьянма": [22.0, 98.0],
    "Шри-Ланка": [7.0, 81.0],
    "Непал": [28.0, 84.0],
    "Бутан": [27.5, 90.5],
    "Мальдивы": [3.0, 73.0],
    "Австралия": [-25.0, 135.0],
    "Новая Зеландия": [-41.0, 174.0],
    "Фиджи": [-18.0, 179.0],
    "Соломоновы Острова": [-9.0, 160.0],
    "Вануату": [-16.0, 167.0],
    "Самоа": [-13.5, -172.0],
    "Тонга": [-20.0, -175.0],
    "Кирибати": [1.0, 173.0],
    "Микронезия": [7.0, 158.0],
    "Маршалловы Острова": [7.0, 171.0],
    "Палау": [7.5, 134.5],
    "Науру": [-0.5, 166.9],
    "Тувалу": [-8.0, 179.0],
    
    # Исторические территории
    "Британская Восточная Африка": [1.0, 37.0],
    "Французский Индокитай": [15.0, 105.0],
    "Российская Империя": [55.0, 60.0],
    "СССР": [55.0, 60.0],
    "Австро-Венгрия": [47.0, 15.0],
    "Османская Империя": [39.0, 35.0],
}


# ===== КОДЫ СТРАН (ISO 3166-1 alpha-3) =====
COUNTRY_CODES = {
    "Южно-Африканская Республика": "ZAF",
    "Трансвааль": "ZAF",
    "Республика Трансвааль": "ZAF",
    "Россия": "RUS",
    "США": "USA",
    "Великобритания": "GBR",
    "Германия": "DEU",
    "Франция": "FRA",
    "Италия": "ITA",
    "Испания": "ESP",
    "Португалия": "PRT",
    "Нидерланды": "NLD",
    "Бельгия": "BEL",
    "Швейцария": "CHE",
    "Австрия": "AUT",
    "Швеция": "SWE",
    "Норвегия": "NOR",
    "Финляндия": "FIN",
    "Дания": "DNK",
    "Польша": "POL",
    "Чехия": "CZE",
    "Словакия": "SVK",
    "Венгрия": "HUN",
    "Греция": "GRC",
    "Ирландия": "IRL",
    "Украина": "UKR",
    "Беларусь": "BLR",
    "Литва": "LTU",
    "Латвия": "LVA",
    "Эстония": "EST",
    "Румыния": "ROU",
    "Болгария": "BGR",
    "Сербия": "SRB",
    "Хорватия": "HRV",
    "Словения": "SVN",
    "Албания": "ALB",
    "Молдова": "MDA",
    "Исландия": "ISL",
    "Мальта": "MLT",
    "Кипр": "CYP",
    "Турция": "TUR",
    "Канада": "CAN",
    "Мексика": "MEX",
    "Бразилия": "BRA",
    "Аргентина": "ARG",
    "Чили": "CHL",
    "Колумбия": "COL",
    "Венесуэла": "VEN",
    "Перу": "PER",
    "Эквадор": "ECU",
    "Боливия": "BOL",
    "Парагвай": "PRY",
    "Уругвай": "URY",
    "Гайана": "GUY",
    "Суринам": "SUR",
    "Куба": "CUB",
    "Ямайка": "JAM",
    "Гаити": "HTI",
    "Доминикана": "DOM",
    "Китай": "CHN",
    "Япония": "JPN",
    "Индия": "IND",
    "Южная Корея": "KOR",
    "Северная Корея": "PRK",
    "Вьетнам": "VNM",
    "Таиланд": "THA",
    "Малайзия": "MYS",
    "Индонезия": "IDN",
    "Филиппины": "PHL",
    "Пакистан": "PAK",
    "Бангладеш": "BGD",
    "Мьянма": "MMR",
    "Непал": "NPL",
    "Бутан": "BTN",
    "Шри-Ланка": "LKA",
    "Монголия": "MNG",
    "Казахстан": "KAZ",
    "Киргизия": "KGZ",
    "Таджикистан": "TJK",
    "Туркменистан": "TKM",
    "Узбекистан": "UZB",
    "Афганистан": "AFG",
    "Иран": "IRN",
    "Ирак": "IRQ",
    "Сирия": "SYR",
    "Ливан": "LBN",
    "Израиль": "ISR",
    "Иордания": "JOR",
    "Саудовская Аравия": "SAU",
    "Йемен": "YEM",
    "Оман": "OMN",
    "ОАЭ": "ARE",
    "Катар": "QAT",
    "Кувейт": "KWT",
    "Бахрейн": "BHR",
    "Египет": "EGY",
    "ЮАР": "ZAF",
    "Нигерия": "NGA",
    "Кения": "KEN",
    "Танзания": "TZA",
    "Уганда": "UGA",
    "Эфиопия": "ETH",
    "Сомали": "SOM",
    "Судан": "SDN",
    "Алжир": "DZA",
    "Марокко": "MAR",
    "Тунис": "TUN",
    "Ливия": "LBY",
    "Мавритания": "MRT",
    "Сенегал": "SEN",
    "Мали": "MLI",
    "Буркина-Фасо": "BFA",
    "Нигер": "NER",
    "Чад": "TCD",
    "Камерун": "CMR",
    "Габон": "GAB",
    "ДР Конго": "COD",
    "Ангола": "AGO",
    "Намибия": "NAM",
    "Ботсвана": "BWA",
    "Зимбабве": "ZWE",
    "Замбия": "ZMB",
    "Мозамбик": "MOZ",
    "Мадагаскар": "MDG",
    "Австралия": "AUS",
    "Новая Зеландия": "NZL",
    "Папуа - Новая Гвинея": "PNG",
    "Фиджи": "FJI",
    "Соломоновы Острова": "SLB",
    "Вануату": "VUT",
    "Самоа": "WSM",
    "Тонга": "TON",
    "Кирибати": "KIR",
    "Микронезия": "FSM",
    "Маршалловы Острова": "MHL",
    "Палау": "PLW",
    "Науру": "NRU",
    "Тувалу": "TUV",
    
    # Островные территории
    "Нидерландские Антильские острова": "ANT",
    "Аруба": "ABW",
    "Кюрасао": "CUW",
    "Синт-Мартен": "SXM",
}
# === ИСТОРИЧЕСКИЕ СТРАНЫ С 1600 ГОДА (из отдельного файла) ===
from utils.historical_countries import (
    HISTORICAL_COUNTRIES_FROM_1600,
    HISTORICAL_SUCCESSOR_ENGLISH,
    HISTORICAL_SUCCESSOR_ALTERNATIVES,
    MODERN_COUNTRIES_RU_TO_EN,
)

# Английские названия преемников (основные)
for _ru, _en in HISTORICAL_SUCCESSOR_ENGLISH.items():
    RUSSIAN_TO_ENGLISH.setdefault(_ru, _en)
    ENGLISH_TO_RUSSIAN.setdefault(_en, _ru)

# Альтернативные английские названия (варианты имён в разных GeoJSON)
for _ru, _alts in HISTORICAL_SUCCESSOR_ALTERNATIVES.items():
    _cur = COUNTRY_NAME_ALTERNATIVES.setdefault(_ru, [])
    for _a in _alts:
        if _a not in _cur:
            _cur.append(_a)

# Все современные страны мира (для карты и диалога преемственности)
for _ru, _en in MODERN_COUNTRIES_RU_TO_EN.items():
    RUSSIAN_TO_ENGLISH.setdefault(_ru, _en)
    ENGLISH_TO_RUSSIAN.setdefault(_en, _ru)

# Слияние исторических стран в HISTORICAL_MAPPING
# (setdefault: записи БД и старого маппинга имеют приоритет)
for _name, _succ in HISTORICAL_COUNTRIES_FROM_1600.items():
    HISTORICAL_MAPPING.setdefault(_name, _succ)
    
    
# === КООРДИНАТЫ МИКРО-СТРАН И ТЕРРИТОРИЙ (для маркеров на карте) ===
COUNTRY_COORDINATES.update({
    'Андорра': [42.5, 1.5],
    'Британские Виргинские острова': [18.4, -64.6],
    'Ватикан': [41.9, 12.45],
    'Гибралтар': [36.14, -5.35],
    'Гонконг': [22.3, 114.2],
    'Джерси': [49.2, -2.1],
    'Нидерландские Антильские острова': [12.2, -68.3],
    'Остров Мэн': [54.2, -4.5],
    'Острова Кука': [-21.2, -159.8],
    'Острова Питкэрн': [-24.7, -127.4],
    'Острова Святой Елены и Вознесения': [-15.95, -5.7],
    'Сан-Марино': [43.94, 12.46],
    'Тристан-да-Кунья': [-37.1, -12.3],
    'Фолклендские острова': [-51.8, -59.0],
    'Южная Георгия': [-54.5, -37.0],
    'Монако': [43.73, 7.42],
    'Лихтенштейн': [47.16, 9.55],
    'Мальта': [35.9, 14.4],
    'Макао': [22.2, 113.55],
    'Палестина': [31.9, 35.2],
    'Косово': [42.6, 21.0],
    'Тайвань': [23.7, 120.9],
    'Гренландия': [71.7, -42.6],
})